config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  get 'sessions/index', as: :login
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout
  get 'articles/scrape', as: :scraper
  get 'admin/scrape', to: 'articles#scrape', as: :admin_scrape
  get 'articles/interests', to: 'articles#interests', as: :interests
  get 'articles/search', as: :search
  get 'email', to: 'articles#user_email', as: :user_email
  get 'admin/email', to: 'articles#admin_email', as: :admin_email

  resources :articles, only: [:create, :index, :show]
  resources :users, only: [:new, :create, :edit, :update, :destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, uniqueness: { case_sensitive: false }
  belongs_to :source
  belongs_to :author
  acts_as_taggable
end

app/controllers/articles_controller.rb
require 'date'
require_relative '../models/tgjson_importer'
require_relative '../models/tarss_importer'
require_relative '../models/hsrss_importer'
require_relative '../models/tnjson_importer'
require_relative '../models/search/search_engine'
# ArticlesController
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user, except: [:admin_email, :scrape]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def search
    return redirect_to articles_path if params[:q].nil?

    @articles = SearchEngine.do_search(params[:q])
    render 'index'
  end

  def user_email
    unless curr_user.subscribed
      return redirect_to(edit_user_path(curr_user.id),
                         alert: 'please subscribe to digest first')
    end

    articles = Article.tagged_with(curr_user.interest_list, any: true)
    if articles.empty?
      DigestMailer.empty_news(curr_user).deliver
    else
      DigestMailer.email(articles, curr_user).deliver
    end
    redirect_to interests_path,
                notice: 'The digest has been sent to your email address'
  end

  def admin_email
    pairs = []
    subscribers = User.where(subscribed: true)
    subscribers.each do |sb|
      pairs << [Article.tagged_with(sb.interest_list, any: true), sb]
    end
    pairs.each do |articles, user|
      if articles.empty?
        DigestMailer.empty_news(user).deliver
      else
        DigestMailer.email(articles, user).deliver
      end
    end

    redirect_to articles_path,
                notice: 'The digest has been sent to all subscribers'
  end

  def interests
    @articles = Article.tagged_with(curr_user.interest_list, any: true)
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  def scrape
    start_date = Date.today - 7
    end_date = Date.today
    importers = []
    importers << TgJsonImporter.new(start_date, end_date)
    importers << TaRssImporter.new(start_date, end_date)
    importers << HsRssImporter.new(start_date, end_date)
    # importers << BbRssImporter.new(start_date, end_date)
    importers << TnJsonImporter.new(start_date, end_date)
    # importers << TeRssImporter.new(start_date, end_date)
    # importers << BbcRssImporter.new(start_date, end_date)

    importers.each(&:scrape)
    redirect_to articles_path, notice: 'refresh complete!'
  end

  # # GET /articles/1/edit
  # def edit
  # end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html do
          redirect_to @article, notice: 'Article was successfully created.'
        end
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:source_id, :title, :date_of_publication,
                                    :summary, :author_id, :image, :link)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_main.erb
<br>
<%= form_tag("/articles/search", method: "get") do %>
  <div class="input-group">
    <%= text_field_tag :q, nil, class: 'form-control', placeholder: 'Search keywords separated by comma' %>
    <span class="input-group-btn">
      <%= submit_tag("Search", class:"btn btn-info") %>
    </span>
  </div>
<% end %>
<br>
<%= link_to 'REFRESH', scraper_path, class:"btn btn-info btn-lg btn-block" %>
<br>
<br>
<% @articles.each do |article| %>
  <%= render partial: 'panel', locals: {article: article} %>
<% end %>

app/views/articles/_panel.erb
<div class="panel panel-default">
  <div class="panel-body">
  	<h2><%= article.title %></h2>
    <h3><small>Published On: <%= article.date_of_publication%></small></h3>
  	<p><%= article.summary %></p>
  	<div class="btn-group pull-right" role="group">
	  	<%= link_to 'Show', article, class: "btn btn-default" %>
	  </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-xs-5">
        <% if article.author %>
          By <%=article.author.name %>,
        <% end %>
        <%= article.source.name %>
      </div>
      <div class="col-xs-7">
        <% unless article.tag_list.empty? %>
          <% article.tag_list.each do |tag| %>
            <div class="pull-right">
              <button type="button" class="btn btn-default btn-xs"><%= tag %></button>&nbsp;
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= render 'main' %>

app/views/articles/interests.erb
<h1>Articles in Interests</h1>

<%= render 'main' %>

app/views/articles/show.html.erb
<!--
<% @article.attributes.each_pair do |key, val| %>
  <% if val && !['id','source_id','created_at','updated_at'].include?(key)  %>
    <h2><%= key %></h2>
    <p><%= val %></p>
  <% end %>
<% end %> -->
<h1><%= @article.title %></h1>
<h3>
  <small><%= @article.date_of_publication %>, </small>
  <% if @article.author %>
    <small><%= @article.author.name %>, </small>
  <% end %>
  <small><%= @article.source.name %></small>
</h3>
<br>
<div class="well">
  <%= image_tag(@article.image,class:"img-responsive") %>
  <br>
  <h5><%= @article.summary %></h5>
  <br>
  <div class="row">
    <div class="col-xs-2">
      <%= link_to 'read more', @article.link, class:"btn btn-default btn-sm", target:'_blank' %>
    </div>
    <div class="col-xs-10">
      <% unless @article.tag_list.empty? %>
        <% @article.tag_list.each do |tag| %>
          <div class="pull-right">
            <button type="button" class="btn btn-default btn-xs"><%= tag %></button>&nbsp;
          </div>
        <% end %>
      <% end %>
    </div>
</div>
</div>
<br>
<%= link_to 'Back', :back, class:"btn btn-default" %>