config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  get 'sessions/index', as: :login
  post 'sessions/login', as: :signin
  delete 'sessions/logout', as: :logout
  get 'articles/scrape', as: :scraper
  get 'admin/scrape', to: 'articles#scrape', as: :admin_scrape
  get 'articles/interests', to: 'articles#interests', as: :interests
  get 'articles/search', as: :search
  get 'email', to: 'articles#user_email', as: :user_email
  get 'admin/email', to: 'articles#admin_email', as: :admin_email

  resources :articles, only: [:create, :index, :show]
  resources :users, only: [:new, :create, :edit, :update, :destroy]

end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'The Digest',login_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if curr_user %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to 'Articles in Interests', interests_path %></li>
        </ul>
        <%= link_to 'Send Digest', user_email_path, class: 'btn btn-default navbar-btn' %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Welcome! #{curr_user.first_name}", edit_user_path(curr_user.id) %></li>
          <li><%= link_to "Edit Profile", edit_user_path(curr_user.id)%></li>
          <li><%= link_to "Log Out", logout_path, method: :delete%></li>
        </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Digest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: '/layouts/nav_bar' %>
  <div class="container">
    <% flash.each do |name, msg| -%>
      <% if name == 'notice' %>
        <%= content_tag :div, msg, class: "alert alert-success" %>
      <% elsif name == 'alert' %>
        <%= content_tag :div, msg, class: "alert alert-danger" %>
      <% else %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
    <% end -%>
  	<%= yield %>
  </div>

</body>
</html>